#!/usr/bin/env bash

echo "music-lib Disk Space Checker version 1.0.1"

oldpwd="$(pwd)"
cd "$(dirname "$0")" || exit 1
echo "Music takes up $(du -shc ./music | cut -f1 | head -n 1) of space."
cd "$oldpwd" || exit 1
