#!/usr/bin/env bash

set -e

echo "music-lib Downloader version 2.0"

showhelp() {
    echo " --help : View this help"
    echo " --verbose : Verbose output"
    echo " --inf-retries : Infinite retries"
}

is_verbose=0
inf_retries=0

# arg parsing
while [[ $# -gt 0 ]]; do
    case $1 in
        --verbose)
            is_verbose=1
            shift
            ;;
        --inf-retries)
            inf_retries=1
            shift
            ;;
        --help)
            showhelp
            exit 1
            ;;
        *)
            echo "Unrecognized Argument: $1"
            echo "See $0 --help for help."
            exit 2
            ;;
    esac
done

# check if yt dlp is installed
if ! command -v yt-dlp &>/dev/null; then
    echo "E: \`yt-dlp' is not installed, please install it"
    exit 1
fi

script_dir_rel="$(dirname "$0")"
script_dir="$(realpath $script_dir_rel)"

while IFS= read -r line <&3 || [ -n "$line" ]; do
	cd "$(dirname "$0")"

    # skip empty lines
    [[ -z "$line" ]] && continue

    PlaylistId=$(echo "$line" | awk '{print $1}')
    Folder=$(echo "$line" | awk '{print $2}')

    mkdir -p "$script_dir/$Folder"
    
    echo "Downloading playlist: $PlaylistId into $Folder"
    
    additional_args=""
    
    [ "$is_verbose" == "1" ] && additional_args="$additional_args -v"
    [ "$inf_retries" == "1" ] && additional_args="$additional_args -R infinite"

	cd "$script_dir/$Folder"
    yt-dlp -i "$PlaylistId" --cookies-from-browser firefox --yes-playlist --download-archive archive.txt -f bestaudio --progress -o "%(title)s.%(ext)s" $additional_args || true
	cd "$script_dir"
done 3< "$script_dir/PlaylistId.txt"